load("@io_bazel_rules_rust//rust:rust.bzl", "rust_binary")

cc_binary(
  name="advent-01",
  srcs=["advent-01.cc"],
  data=["input01.txt"]
)

rust_binary(
  name="day1_part1",
  srcs=["day1_part1.rs"],
  data=["input01.txt"]
)

rust_binary(
  name="day1_part2",
  srcs=["day1_part2.rs"],
  data=["input02.txt"]
)
