load("@io_bazel_rules_rust//rust:rust.bzl", "rust_binary")

rust_binary(
  name="part1",
  srcs=["part1.rs"],
  data=["input.txt"]
)

rust_binary(
  name="part2",
  srcs=["part2.rs"],
  data=["input.txt"]
)
