load("@io_bazel_rules_rust//rust:rust.bzl", "rust_binary")

rust_binary(
  name="day2_part1",
  srcs=["day2_part1.rs"],
  data=["input01.txt"]
)

rust_binary(
  name="day2_part2",
  srcs=["day2_part2.rs"],
  data=["input01.txt"]
)
